version: '3.8'

services:
  chunk-generator:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
