server {
    listen 8090;

    # Health check
    location /health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # HLS stream proxied from SRS
    location /live/ {
        proxy_pass http://random-streamer-srs:8080/;
        proxy_set_header Host $host;
        proxy_buffering off;
        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin * always;
    }

    # Flutter web UI
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
